### ISSUE TITLE
Did you tried to turn off default request logging in .net and then compare results?<EOM>

### ISSUE THREAD

**Issue by uhrb** [anjmao/netcore-vs-golang#1]

**Comment by anjmao** [comment]
@l0nley Yes, I updated tests results to use https://github.com/anjmao/netcore-vs-golang/blob/master/netcore/Program.cs#L25 but it didn't helped :)

**Comment by uhrb** [comment]
`
.ConfigureLogging(logging => logging.ClearProviders()) 
`
Thats how you can do it.

**Comment by anjmao** [comment]
Yep, I also tried clearing logging providers and it doesn't affect performance at all (which is good).

**Comment by dennis-8** [comment]
Sorry, just want to confirm - asp.net core is more performant?
